# Generated by Django 2.0.7 on 2018-07-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comp_Name', models.CharField(max_length=50)),
                ('Commission_Date', models.DateField(auto_now_add=True)),
                ('Decommission_Date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cust_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateField(auto_now_add=True)),
                ('Ship_Date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_Name', models.SlugField()),
                ('Remaining_Budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Is_Supervisor', models.BooleanField(default=False)),
                ('Employee_Is_Active', models.BooleanField(default=True)),
                ('Comp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Computer')),
                ('Dept_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed', models.BooleanField(default=False)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employment_Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hire_Date', models.DateField(auto_now_add=True)),
                ('Term_Date', models.DateField(blank=True)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Cust_Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Type_Name', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=350)),
                ('Price', models.PositiveIntegerField()),
                ('Description', models.CharField(max_length=350)),
                ('Quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Type_Name', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Training_Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Name', models.SlugField()),
                ('Program_Description', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Program_Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Start_Date', models.DateField()),
                ('Program_End_Date', models.DateField()),
                ('Max_Students', models.PositiveIntegerField()),
                ('Program_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Training_Program')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.PositiveIntegerField()),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Last_Signon', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Seller_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='Type_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Product_Type'),
        ),
        migrations.AddField(
            model_name='payment_options',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.User'),
        ),
        migrations.AddField(
            model_name='payment_options',
            name='Payment_Type_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Payment_Type'),
        ),
        migrations.AddField(
            model_name='ordered_products',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Product'),
        ),
        migrations.AddField(
            model_name='employee_training',
            name='Session_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Training_Program'),
        ),
        migrations.AddField(
            model_name='cust_order',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.User'),
        ),
        migrations.AddField(
            model_name='cust_order',
            name='Payment_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Payment_Options'),
        ),
    ]
