# Generated by Django 2.0.7 on 2018-07-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comp_Name', models.CharField(max_length=350)),
                ('Commission_Date', models.CharField(max_length=350)),
                ('Decommission_Date', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_Name', models.CharField(max_length=350)),
                ('Remaining_Budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=350)),
                ('Last_Name', models.CharField(max_length=350)),
                ('Employee_Is_Active', models.BooleanField()),
                ('Comp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Computer')),
                ('Dept_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='Supervisor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Employee'),
        ),
    ]
