# Generated by Django 2.0.7 on 2018-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_type',
            name='Payment_Type_Name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Product_Type_Name',
            field=models.SlugField(),
        ),
    ]
